/* tslint:disable */
/* eslint-disable */
/**
 * Chabloom Accounts
 * Chabloom Accounts v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterViewModel
 */
export interface RegisterViewModel {
    /**
     * 
     * @type {string}
     * @memberof RegisterViewModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterViewModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterViewModel
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterViewModel
     */
    password: string;
}

export function RegisterViewModelFromJSON(json: any): RegisterViewModel {
    return RegisterViewModelFromJSONTyped(json, false);
}

export function RegisterViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'],
        'password': json['password'],
    };
}

export function RegisterViewModelToJSON(value?: RegisterViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'phone': value.phone,
        'password': value.password,
    };
}


